version: "3"

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  api:
    build:
      context: ./films-api
      dockerfile: ./Dockerfile
      args:
        API_PORT: ${API_PORT:-4000}
    image: films-api
    env_file:
      - ./films-api/.env
    environment:
      DB_HOSTNAME: database
    ports:
      - "4000:${API_PORT:-4000}"
    volumes:
      - type: bind
        source: ./films-api/src
        target: /films-api/src
    depends_on:
      - database

  frontend:
    build:
      context: ./films-ui
      dockerfile: ./Dockerfile
      args:
        UI_PORT: ${UI_PORT:-3000}
    image: films-ui
    environment:
      API_HOST: "api:${API_PORT:-4000}"
      #react expects PORT variable name to setup app on
      PORT: ${UI_PORT:-3000}
    ports:
      - "8080:${UI_PORT:-3000}"
    volumes:
      - type: bind
        source: ./films-ui/src
        target: /films-ui/src
    depends_on:
      - api

volumes:
  pgdata:
